/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const CadastroCategoriaLazyImport = createFileRoute('/cadastro-categoria')()
const CadastrarProdutoLazyImport = createFileRoute('/cadastrar-produto')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const CadastroCategoriaLazyRoute = CadastroCategoriaLazyImport.update({
  path: '/cadastro-categoria',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cadastro-categoria.lazy').then((d) => d.Route),
)

const CadastrarProdutoLazyRoute = CadastrarProdutoLazyImport.update({
  path: '/cadastrar-produto',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cadastrar-produto.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cadastrar-produto': {
      preLoaderRoute: typeof CadastrarProdutoLazyImport
      parentRoute: typeof rootRoute
    }
    '/cadastro-categoria': {
      preLoaderRoute: typeof CadastroCategoriaLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CadastrarProdutoLazyRoute,
  CadastroCategoriaLazyRoute,
  LoginLazyRoute,
])

/* prettier-ignore-end */
